# Cableonda/AdmininBundle/Resources/config/admin.yml
services:
    sonata.admin.logslogin:
        class: Cableonda\AdmininBundle\Admin\LogsloginAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Logs", label: "Inicio de Sesi√≥n",show_in_dashboard: false  }
        arguments:
            - ~
            - Cableonda\AdmininBundle\Entity\Logslogin
            - ~
        calls:
            - [ setTranslationDomain, [AdmininBundle]]
